export enum Routes {
  LOGIN = 'ENTRADA',
  REGISTER = 'REGISTRO',
  HOME = 'PRINCIPAL',
  INVENTARIO = 'INVENTÁRIO',
  POST_ARTIGO = 'CRIAR-ARTIGO',
  EDIT_ARTIGO = 'EDITAR-ARTIGO',
  ARTIGO = 'ARTIGOS',
}
export enum Cargo {
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export enum Sexo {
  MASCULINO = 'MASCULINO',
  FEMININO = 'FEMININO',
}
