export enum Routes {
  LOGIN = 'ENTRADA',
  REGISTER = 'REGISTRO',
  HOME = 'PRINCIPAL',
  INVENTARIO = 'INVENTÁRIO',
  POST_ARTIGO = 'CRIAR-ARTIGO',
  EDIT_ARTIGO = 'EDITAR-ARTIGO',
  ARTIGO = 'ARTIGOS',
  // Painel de Controle de Usuários
  USER_ADMIN = 'USUARIO_ADMIN',
  USER_LIST = 'LISTA_USUARIO',
  POST_USER = 'REGISTRAR_USUARIO',
  ACCOUNTING = 'CONTABILIDADE',
  EDIT_USER = 'ALTERAR_USUARIO',
  SALE = 'VENDA',
  BOX_SALE = 'CAIXA',
  SALE_ARTICLES = 'LISTA_ARTIGOS_VENDA',
  CONFIGURATION = 'CONFIGURACOES',
  // USERS = 'USUARIOS',
}
export enum Cargo {
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export enum Sexo {
  MASCULINO = 'MASCULINO',
  FEMININO = 'FEMININO',
}
